import type { CategorySlug } from "./data/categories";
import { categories } from "./data/categories";

/** Public base URL for Cloudflare R2 bucket `TNH-media`. Empty until you paste the URL. */
export const R2: string = "https://pub-6b086f2686134300918c3ecd2486025c.r2.dev";

/** True once brand marks are uploaded. Category covers are mapped separately. */
export const hasRemoteMedia = false;

/* Hero film is cross-origin. Keep preload="metadata" and a poster. When you switch to R2, set a CORS rule
   on the bucket (GET from your Pages domain) if the player needs to read the file as a canvas/CORS resource. */

const HERO_VIDEO =
  "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260818_072341_50851634-bbc3-4c33-9acc-7647d4db44aa.mp4";

export const hasHeroVideo = true;

const r2 = (path: string) => (R2 ? `${R2.replace(/\/$/, "")}/${path}` : "");

const FALLBACK_COVER = "/placeholders/category.svg";

/** Object keys on R2. Construction is capitalized in the bucket. */
const categoryCoverFiles: Record<CategorySlug, string> = {
  safety: "safety.jfif",
  pneumatic: "pneumatic.jfif",
  tools: "tools.jfif",
  construction: "Construction.jfif",
  welding: "welding.jfif",
  steel: "steel.jfif",
  hvac: "hvac.jfif",
  electronics: "electronics.jfif",
  electrical: "electrical.jfif",
  pipes: "pipes.jfif",
  janitorial: "janitorial.jfif",
  lubricants: "lubricants.jfif",
  medical: "medical.jfif",
};

const categoryCovers = Object.fromEntries(
  categories.map((c) => [c.slug, r2(`categories/${categoryCoverFiles[c.slug]}`) || FALLBACK_COVER]),
) as Record<CategorySlug, string>;

export function categoryCover(slug: CategorySlug): string {
  return categoryCovers[slug];
}

/** Optional product stills. Paths are the object keys already on R2. */
const categoryGalleries: Partial<Record<CategorySlug, string[]>> = {
  safety: [
    "products/safety/1.jfif",
    "products/safety/2.jfif",
    "products/safety/3.jfif",
    "products/safety/4.jfif",
    "products/safety/5.jfif",
    "products/safety/6.jfif",
    "products/safety/7.jfif",
    "products/safety/8.jfif",
    "products/safety/9.jfif",
    "products/safety/10.jfif",
    "products/safety/11.jfif",
    "products/safety/12.jfif",
    "products/safety/13.jfif",
    "products/safety/14.jfif",
    "products/safety/15.jfif",
    "products/safety/16.jfif",
    "products/safety/17.jfif",
    "products/safety/37.jfif",
    "products/safety/18.jfif",
    "products/safety/19.jfif",
    "products/safety/20.jfif",
    "products/safety/21.jfif",
    "products/safety/22.jfif",
    "products/safety/23.jfif",
    "products/safety/24.jfif",
    "products/safety/25.jfif",
    "products/safety/26.jfif",
    "products/safety/27.jfif",
    "products/safety/28.jfif",
    "products/safety/29.jfif",
    "products/safety/30.jfif",
    "products/safety/35.jfif",
    "products/safety/36.jfif",
    "products/safety/31.jfif",
    "products/safety/32.jfif",
    "products/safety/33.jfif",
    "products/safety/34.jfif",
  ],
  pneumatic: [
    "products/pneumatic/1.png",
    "products/pneumatic/2.png",
    "products/pneumatic/3.png",
    "products/pneumatic/4.png",
    "products/pneumatic/5.png",
    "products/pneumatic/6.png",
    "products/pneumatic/7.png",
    "products/pneumatic/8.png",
    "products/pneumatic/9.png",
    "products/pneumatic/10.png",
    "products/pneumatic/11.jfif",
    "products/pneumatic/12.jfif",
    "products/pneumatic/13.jfif",
    "products/pneumatic/14.jfif",
    "products/pneumatic/15.jfif",
    "products/pneumatic/16.jfif",
    "products/pneumatic/17.jfif",
    "products/pneumatic/18.jfif",
    "products/pneumatic/19.jfif",
    "products/pneumatic/20.jfif",
    "products/pneumatic/21.jfif",
    "products/pneumatic/22.jfif",
    "products/pneumatic/23.jfif",
    "products/pneumatic/24.jfif",
    "products/pneumatic/25.jfif",
    "products/pneumatic/26.jfif",
    "products/pneumatic/27.jfif",
    "products/pneumatic/28.jfif",
    "products/pneumatic/29.jfif",
    "products/pneumatic/30.jfif",
    "products/pneumatic/31.jfif",
    "products/pneumatic/32.jfif",
    "products/pneumatic/33.jfif",
    "products/pneumatic/34.jfif",
    "products/pneumatic/35.jfif",
    "products/pneumatic/36.jfif",
    "products/pneumatic/37.jfif",
    "products/pneumatic/38.jfif",
    "products/pneumatic/39.jfif",
    "products/pneumatic/40.jfif",
    "products/pneumatic/41.jfif",
  ],
  tools: [
    "products/tools/1.jfif",
    "products/tools/2.jfif",
    "products/tools/3.jfif",
    "products/tools/4.jfif",
    "products/tools/5.jfif",
    "products/tools/6.jfif",
    "products/tools/7.jfif",
    "products/tools/8.jfif",
    "products/tools/9.jfif",
    "products/tools/10.jfif",
    // "products/tools/11.jfif",
    // "products/tools/12.jfif",
    // "products/tools/13.jfif",
    // "products/tools/14.jfif",
    // "products/tools/15.jfif",
    // "products/tools/16.jfif",
    // "products/tools/17.jfif",
    // "products/tools/18.jfif",
    // "products/tools/19.jfif",
    // "products/tools/20.jfif",
    // "products/tools/21.jfif",
    // "products/tools/22.jfif",
    // "products/tools/23.jfif",
    // "products/tools/24.jfif",
    // "products/tools/25.jfif",
    // "products/tools/26.jfif",
    // "products/tools/27.jfif",
    // "products/tools/28.jfif",
    // "products/tools/29.jfif",
    // "products/tools/30.jfif",
    // "products/tools/31.jfif",
    // "products/tools/32.jfif",
    // "products/tools/33.jfif",
    // "products/tools/34.jfif",
    // "products/tools/35.jfif",
    // "products/tools/36.jfif",
    // "products/tools/37.jfif",
    // "products/tools/38.jfif",
    // "products/tools/39.jfif",
    // "products/tools/40.jfif",
    // "products/tools/41.jfif",
  ],

  construction: [
    "products/construction/1.jfif",
    "products/construction/2.jfif",
    "products/construction/3.jfif",
    "products/construction/4.jfif",
    "products/construction/5.jfif",
    "products/construction/6.jfif",
    "products/construction/7.jfif",
    "products/construction/8.jfif",
    "products/construction/9.jfif",
    "products/construction/10.jfif",
    // "products/construction/11.jfif",
    // "products/construction/12.jfif",
    // "products/construction/13.jfif",
    // "products/construction/14.jfif",
    // "products/construction/15.jfif",
    // "products/construction/16.jfif",
    // "products/construction/17.jfif",
    // "products/construction/18.jfif",
    // "products/construction/19.jfif",
    // "products/construction/20.jfif",
    // "products/construction/21.jfif",
    // "products/construction/22.jfif",
    // "products/construction/23.jfif",
    // "products/construction/24.jfif",
    // "products/construction/25.jfif",
    // "products/construction/26.jfif",
    // "products/construction/27.jfif",
    // "products/construction/28.jfif",
    // "products/construction/29.jfif",
    // "products/construction/30.jfif",
    // "products/construction/31.jfif",
    // "products/construction/32.jfif",
    // "products/construction/33.jfif",
    // "products/construction/34.jfif",
    // "products/construction/35.jfif",
    // "products/construction/36.jfif",
    // "products/construction/37.jfif",
    // "products/construction/38.jfif",
    // "products/construction/39.jfif",
    // "products/construction/40.jfif",
    // "products/construction/41.jfif",
  ],

  welding: [
    "products/welding/1.jfif",
    "products/welding/2.jfif",
    "products/welding/3.jfif",
    "products/welding/4.jfif",
    "products/welding/5.jfif",
    "products/welding/6.jfif",
    "products/welding/7.jfif",
    "products/welding/8.jfif",
    "products/welding/9.jfif",
    "products/welding/10.jfif",
    // "products/welding/11.jfif",
    // "products/welding/12.jfif",
    // "products/welding/13.jfif",
    // "products/welding/14.jfif",
    // "products/welding/15.jfif",
    // "products/welding/16.jfif",
    // "products/welding/17.jfif",
    // "products/welding/18.jfif",
    // "products/welding/19.jfif",
    // "products/welding/20.jfif",
    // "products/welding/21.jfif",
    // "products/welding/22.jfif",
    // "products/welding/23.jfif",
    // "products/welding/24.jfif",
    // "products/welding/25.jfif",
    // "products/welding/26.jfif",
    // "products/welding/27.jfif",
    // "products/welding/28.jfif",
    // "products/welding/29.jfif",
    // "products/welding/30.jfif",
    // "products/welding/31.jfif",
    // "products/welding/32.jfif",
    // "products/welding/33.jfif",
    // "products/welding/34.jfif",
    // "products/welding/35.jfif",
    // "products/welding/36.jfif",
    // "products/welding/37.jfif",
    // "products/welding/38.jfif",
    // "products/welding/39.jfif",
    // "products/welding/40.jfif",
    // "products/welding/41.jfif",
  ],

  steel: [
    "products/steel/1.jfif",
    "products/steel/2.jfif",
    "products/steel/3.jfif",
    "products/steel/4.jfif",
    "products/steel/5.jfif",
    "products/steel/6.jfif",
    "products/steel/7.jfif",
    "products/steel/8.jfif",
    "products/steel/9.jfif",
    "products/steel/10.jfif",
    // "products/steel/11.jfif",
    // "products/steel/12.jfif",
    // "products/steel/13.jfif",
    // "products/steel/14.jfif",
    // "products/steel/15.jfif",
    // "products/steel/16.jfif",
    // "products/steel/17.jfif",
    // "products/steel/18.jfif",
    // "products/steel/19.jfif",
    // "products/steel/20.jfif",
    // "products/steel/21.jfif",
    // "products/steel/22.jfif",
    // "products/steel/23.jfif",
    // "products/steel/24.jfif",
    // "products/steel/25.jfif",
    // "products/steel/26.jfif",
    // "products/steel/27.jfif",
    // "products/steel/28.jfif",
    // "products/steel/29.jfif",
    // "products/steel/30.jfif",
    // "products/steel/31.jfif",
    // "products/steel/32.jfif",
    // "products/steel/33.jfif",
    // "products/steel/34.jfif",
  ],

  hvac: [
    "products/hvac/1.jfif",
    "products/hvac/2.jfif",
    "products/hvac/3.jfif",
    "products/hvac/4.jfif",
    "products/hvac/5.jfif",
    "products/hvac/6.jfif",
    "products/hvac/7.jfif",
    "products/hvac/8.jfif",
    "products/hvac/9.jfif",
    "products/hvac/10.jfif",
    // "products/hvac/11.jfif",
    // "products/hvac/12.jfif",
    // "products/hvac/13.jfif",
    // "products/hvac/14.jfif",
    // "products/hvac/15.jfif",
    // "products/hvac/16.jfif",
    // "products/hvac/17.jfif",
    // "products/hvac/18.jfif",
    // "products/hvac/19.jfif",
    // "products/hvac/20.jfif",
    // "products/hvac/21.jfif",
    // "products/hvac/22.jfif",
    // "products/hvac/23.jfif",
  ],

  electronics: [
    "products/electronics/1.jfif",
    "products/electronics/2.jfif",
    "products/electronics/3.jfif",
    "products/electronics/4.jfif",
    "products/electronics/5.jfif",
    "products/electronics/6.jfif",
    "products/electronics/7.jfif",
    "products/electronics/8.jfif",
    "products/electronics/9.jfif",
    "products/electronics/10.jfif",
    // "products/electronics/11.jfif",
    // "products/electronics/12.jfif",
    // "products/electronics/13.jfif",
    // "products/electronics/14.jfif",
  ],
  electrical: [
    "products/electrical/1.jfif",
    "products/electrical/2.jfif",
    "products/electrical/3.jfif",
    "products/electrical/4.jfif",
    "products/electrical/5.jfif",
    "products/electrical/6.jfif",
    "products/electrical/7.jfif",
    "products/electrical/8.jfif",
    "products/electrical/9.jfif",
    "products/electrical/10.jfif",
    // "products/electrical/11.jfif",
    // "products/electrical/12.jfif",
    // "products/electrical/13.jfif",
    // "products/electrical/14.jfif",
    // "products/electrical/15.jfif",
    // "products/electrical/16.jfif",
    // "products/electrical/17.jfif",
    // "products/electrical/18.jfif",
    // "products/electrical/19.jfif",
    // "products/electrical/20.jfif",
    // "products/electrical/21.jfif",
    // "products/electrical/22.jfif",
    // "products/electrical/23.jfif",
    // "products/electrical/24.jfif",
    // "products/electrical/25.jfif",
    // "products/electrical/26.jfif",
    // "products/electrical/27.jfif",
    // "products/electrical/28.jfif",
    // "products/electrical/29.jfif",
    // "products/electrical/30.jfif",
    // "products/electrical/31.jfif",
  ],
  pipes: [
    "products/pipes/1.jfif",
    "products/pipes/2.jfif",
    "products/pipes/3.jfif",
    "products/pipes/4.jfif",
    "products/pipes/5.jfif",
    "products/pipes/6.jfif",
    "products/pipes/7.jfif",
    "products/pipes/8.jfif",
    "products/pipes/9.jfif",
    "products/pipes/10.jfif",
    // "products/pipes/11.jfif",
    // "products/pipes/12.jfif",
    // "products/pipes/13.jfif",
    // "products/pipes/14.jfif",
    // "products/pipes/15.jfif",
    // "products/pipes/16.jfif",
    // "products/pipes/17.jfif",
    // "products/pipes/18.jfif",
    // "products/pipes/19.jfif",
    // "products/pipes/20.jfif",
    // "products/pipes/21.jfif",
    // "products/pipes/22.jfif",
    // "products/pipes/23.jfif",
  ],
};

export function categoryGallery(slug: CategorySlug): string[] {
  return (categoryGalleries[slug] ?? []).map((key) => r2(key));
}

export function brandLogo(slug: CategorySlug): string {
  return r2(`brands/${slug}.png`);
}

/** Drop the mark in `public/` as one of these names. */
export const logoCandidates = [
  "/logo.png",
  "/logo.png",
  "/logo.jpeg",
  "/logo.webp",
  "/logo.svg",
  "/Logo.png",
  "/logo.png",
  "/tnh-logo.png",
  "/TNH-logo.png",
] as const;

export const media = {
  heroVideo: HERO_VIDEO,
  heroPoster: "/hero-poster.jpg",
  logo: logoCandidates[0],
  categories: categoryCovers,
  fallbackCover: FALLBACK_COVER,
} as const;
